[options]
admin_passwd = d3ltal0g
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
http_port = 8069
http_interface = 0.0.0.0